"""4_OrderedEvent

Revision ID: 28d3f30c9b30
Revises: f61521a13a16
Create Date: 2025-10-27 20:59:37.498934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d3f30c9b30'
down_revision: Union[str, Sequence[str], None] = 'f61521a13a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_events', sa.Column('ticketmaster_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_events', 'ticketmaster_id')
    # ### end Alembic commands ###
