"""5_no_ticketmaster_id

Revision ID: 7a9587313b0b
Revises: 28d3f30c9b30
Create Date: 2025-10-27 22:08:02.435666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9587313b0b'
down_revision: Union[str, Sequence[str], None] = '28d3f30c9b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_events', 'ticketmaster_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_events', sa.Column('ticketmaster_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
